"""empty message

Revision ID: 5a089b386a95
Revises: ccbce4dae0f0
Create Date: 2019-10-01 23:51:51.575572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a089b386a95'
down_revision = 'ccbce4dae0f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcels', sa.Column('delivered', sa.Boolean(), nullable=True))
    op.drop_column('parcels', 'orderStatus')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcels', sa.Column('orderStatus', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('parcels', 'delivered')
    # ### end Alembic commands ###
